# Generated by Django 2.2.2 on 2019-06-11 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=255, verbose_name='20% off all products')),
                ('discount', models.FloatField(verbose_name='0.2')),
            ],
        ),
    ]
